version: '3'

services:
  routing_app:
    container_name: routing_app
    restart: always
    build:  # build from parent directory to copy AttendancePro
      context: ../
      dockerfile: ./Backend/routing_app/Dockerfile
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 routing_app:app

  restful_api:
    container_name: restful_api
    restart: always
    build: ./restful_api
    ports:
      - "5001:5001"
    command: gunicorn -w 1 -b 0.0.0.0:5001 restful_api:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - routing_app
